[tool.poetry]
name = "morphers"
version = "0.1.0"
description = ""
authors = ["Play4Honor"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.0"
polars = "^0.20"
numpy = "^1.26"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
